# Example configuration file for GitHub Replace Tool
# Copy this to ~/.go-toolgit/config.yaml or ./config.yaml and customize

github:
  # On-premise GitHub URL (use https://api.github.com for GitHub.com)
  base_url: "https://github.company.com"
  
  # Personal Access Token with repo and team permissions
  # Can also be set via GITHUB_REPLACE_GITHUB_TOKEN environment variable
  token: "ghp_xxxxxxxxxxxxxxxx"
  
  # GitHub organization name
  organization: "my-org"
  
  # Team name within the organization
  team: "my-team"
  
  # API timeout and retry settings
  timeout: "30s"
  max_retries: 3

processing:
  # File patterns to include in processing
  include_patterns:
    - "*.go"
    - "*.java"
    - "*.js"
    - "*.py"
    - "*.ts"
    - "*.jsx"
    - "*.tsx"
    - "*.yaml"
    - "*.yml"
    - "*.json"
    - "*.md"

  # File patterns to exclude from processing
  exclude_patterns:
    - "vendor/*"
    - "node_modules/*"
    - "*.min.js"
    - "*.min.css"
    - ".git/*"
    - "build/*"
    - "dist/*"
    - "target/*"
    - "*.lock"

  # Maximum number of concurrent workers for processing
  max_workers: 4

pull_request:
  # Template for pull request title
  title_template: "chore: automated string replacement"
  
  # Template for pull request body
  body_template: |
    ## Automated String Replacement
    
    This pull request contains automated string replacements performed by the GitHub Replace Tool.
    
    Please review the changes carefully before merging.
    
    ---
    Generated by GitHub Replace Tool

  # Prefix for created branches
  branch_prefix: "auto-replace"
  
  # Whether to automatically merge PRs (not recommended)
  auto_merge: false
  
  # Whether to delete branches after PR is merged
  delete_branch: true

logging:
  # Log level: debug, info, warn, error
  level: "info"
  
  # Log format: text, json
  format: "text"